# Generated by Django 4.1.4 on 2022-12-24 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "UID",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=255)),
                (
                    "Class",
                    models.CharField(
                        choices=[
                            ("9A", " 9A"),
                            ("9B", " 9B"),
                            ("10A", " 10A"),
                            ("10B", " 10B"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DateTime", models.DateTimeField()),
                (
                    "Stud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.student"
                    ),
                ),
            ],
        ),
    ]
