# Generated by Django 4.1.4 on 2022-12-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_entry_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="StudClass",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="StudName",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
