# Generated by Django 4.1.4 on 2023-02-09 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_entry_studclass_entry_studname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="DateTime",
        ),
        migrations.AddField(
            model_name="entry",
            name="Date",
            field=models.DateField(null=True, verbose_name=datetime.date(2023, 2, 9)),
        ),
        migrations.AddField(
            model_name="entry",
            name="Time",
            field=models.TimeField(
                null=True, verbose_name=datetime.time(22, 58, 5, 807079)
            ),
        ),
    ]
