# Generated by Django 4.2.1 on 2023-08-25 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_entry_status_alter_entry_date_alter_entry_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hardware",
            fields=[
                ("HardwareID", models.AutoField(primary_key=True, serialize=False)),
                ("HardwareName", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="entry",
            name="Date",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="StudClass",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="StudName",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="Time",
        ),
        migrations.AddField(
            model_name="entry",
            name="Timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entry",
            name="Status",
            field=models.CharField(
                choices=[("Late", " Late"), ("OnTime", " Ontime")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="Hw",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.hardware",
            ),
            preserve_default=False,
        ),
    ]
