# Generated by Django 4.2.1 on 2023-08-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_hardware_remove_entry_date_remove_entry_studclass_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="Date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
