# Generated by Django 4.2.1 on 2023-08-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_entry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="StudClass",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="StudName",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
