# Generated by Django 4.2.1 on 2023-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_entry_studclass_entry_studname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="Date",
        ),
        migrations.AddField(
            model_name="entry",
            name="Time",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
