# Generated by Django 4.2.1 on 2023-09-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_entry_date_entry_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="Date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
